### PR TITLE
[WIP] README 2.0.0

### PR DESCRIPTION
**Pull request by 3lvis**
Fixes https://github.com/hyperoslo/Form/issues/271

I've been thinking on improving the README to showcase our biggest features and have a banner for each:

- [ ] Fields (Types, Input types)
- [ ] Targets (mention Conditions)
- [ ] Formulas
- [ ] Templates
- [ ] Customization
- [ ] Formatters
- [ ] Validators

----
Elvis, don't forget to push your commits with `[skip ci]`

### CODE REVIEW

**Comment by 3lvis** [comment]
Targets inspiration for cover

shot_1294780511

**Comment by 3lvis** [comment]
# Cover: Formula inspiration

scriptylab-ab

flask5b_o1

**Comment by 3lvis** [comment]
# Cover: Template inspiration

Here I thought we could have a wired framed version of a Form

screen shot 2015-04-17 at 7 42 00 am

**Comment by 3lvis** [comment]
# Cover: Customization Inspiration

It doesn't have to be in this angle but having many layers of a form in different styles would be kind of cool

seethrough_infinity

**Comment by 3lvis** [comment]
# Cover: Formatter Inspiration

This is a difficult one, I guess we could just have a cool version of this, although we are talking more about how you format bank account numbers, phone numbers and so on.

screen shot 2015-04-17 at 7 48 10 am

**Comment by 3lvis** [comment]
# Cover: Validators inspiration

I think any checkmark would do

screen shot 2015-04-17 at 7 50 46 am

**Comment by richardoti** [comment]
Why this closed? So beautiful!

**Comment by 3lvis** [comment]
Closing down, let's reconsider if a Swift rewrite ever happens.

**Pull request closed without merging**
