### PR TITLE
[WIP] Allow dot entry in float string

### PR DESCRIPTION
**Pull request by jeffleeismyhero**
The dot is currently replaced with a comma upon entry. This maintains existing functionality and adds support for automatically converting a dot to a comma.

Refer to #54

### CODE REVIEW

**Comment by jeffleeismyhero** [comment]
An NSNumberFormatter can now be passed to FORMFloatFormatter for custom number formatting.

Form fields can also customize the NSNumberFormatter using the attributes below.

___

#### ```positiveFormat```
Format of positive numbers

**Examples:**
- ```@"#,###.##"```
  - 1234.56 => 1,234.56
  - 1234.00 => 1,234
- ```@"###.00"```
  - 1234.56 => 1234.56
  - 1234.00 => 1234.00
- ```@"$#,###.00"```
  - 1234.56 => $1,234.56
  - 1234.00 => $1,234.00

___

#### ```negativeFormat```
Format of negative numbers (defaults to positiveFormat with a - in front)

**Examples:**
- ```@"(#,###.##)"```
  - -1234.56 => (1,234.56)
  - -1234.00 => (1,234)

___

#### ```groupingSeparator```
Separator for whole numbers (e.g., 1,000.00 or 1 000,00)

**Examples (assuming positiveFormat of ```@"#,###.##"```):**
- ```@" "```
  - 1234.56 => 1 234.56
  - 123456789.00 => 123 456 789
- ```@","```
  - 1234.56 => 1,234.56
  - 123456789.00 => 123,456,789

___

#### ```decimalSeparator```
Separator for decimal place (e.g., 1.23 or 1,23)

**Examples (assuming positiveFormat of ```@"#,###.##"```):**
- ```@","```
  - 1.23 => 1,23
- ```@"."```
  - 1.23 => 1.23

**Comment by 3lvis** [comment]
@jeffleeismyhero Hey Jeff, this looks great! What's left to remove the `[WIP]` prefix from the PR name?

**Comment by jeffleeismyhero** [comment]
@3lvis the current progress does not address the fields themselves. I'm also working through issues relating to optional decimal places.

**Comment by jeffleeismyhero** [comment]
It seems like the only way to reliably handle formatting in the field would be to delay taking action until resignFirstResponder. Otherwise, the decimal values result in odd behavior.

It appears that this would only affect realtime formatting and triggers as keys are pressed. If you have a price, quantity, and total (price * quantity) fields, the triggers are executed at each key press, thus entering "10.50" for price would result in something like this:

10 (price) * 1 (quantity) = 10.00 (total)
10.50 (price) * 1 (quantity) = 10.50 (total)

**Comment by jeffleeismyhero** [comment]
Hit submit too soon. The changes required for formats would allow the following:

positiveFormat: @"$#,###.00"
decimalSeparator: @"."
groupingSeparator: @","

Price field (typed): 1234.5
-- resignFirstResponder
Price field (formatted): $1,234.50

**Comment by jeffleeismyhero** [comment]
Since it's been a while since I worked on this, I've rebased it against the master branch and squashed the commits into one.

I'm going to focus on the minimum functionality of just changing the decimal separator for now and will continue to explore full formatting as time permits.

**Comment by 3lvis** [comment]
@jeffleeismyhero Looking forward to get this on `master`, :star2: :cake: :star2:

**Comment by jeffleeismyhero** [comment]
This PR now allows for custom Decimal Separators at a per-field level.

Adding `"decimal_separator":"."` to a field's JSON hash will configure that field to use a period/dot (`.`) as the decimal separator.

Leaving the `decimal_separator` attribute blank will result in the default behavior of Form, which features a comma (`,`) as the decimal separator.

```json
{
  "groups":[
    {
      "id":"formatted-floats",
      "title":"Formatted Floats",
      "sections":[
        {
          "id":"formatted-floats-0",
          "fields":[
            {
              "id":"float_default",
              "title":"Float Default",
              "info":"Default Separators",
              "type":"float",
              "value":"1,00",
              "size":{
                "width":25,
                "height":1
              },
              "targets":[
                {
                  "id":"float_default_target",
                  "type":"field",
                  "action":"update"
                }
              ]
            },
            {
              "id":"float_default_target",
              "title":"Float Default - Target",
              "info":"Default Separators",
              "type":"float",
              "formula":"$float_default",
              "disabled":true,
              "size":{
                "width":25,
                "height":1
              }
            },
            {
              "id":"float_custom",
              "title":"Float Custom",
              "info":"US Separators",
              "type":"float",
              "value":"1.00",
              "size":{
                "width":25,
                "height":1
              },
              "decimal_separator":".",
              "targets":[
                {
                  "id":"float_custom_target",
                  "type":"field",
                  "action":"update"
                }
              ]
            },
            {
              "id":"float_custom_target",
              "title":"Float Custom - Target",
              "info":"US Separators",
              "type":"float",
              "formula":"$float_custom",
              "disabled":true,
              "size":{
                "width":25,
                "height":1
              },
              "decimal_separator":"."
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by zenangst** [comment]
@jeffleeismyhero still a `[WIP]`? Any bits missing?

**Comment by jeffleeismyhero** [comment]
@zenangst There are essentially four parts to what I'm looking to do; each is listed below. The first part is done and works well.

1. Decimal separators (finished)
2. Grouping separators (almost there)
3. Positive number formats (bugs with optional decimal digits)
4. Negative number formats (same as 3)

Theoretically, this could be merged now and people would be able to make use of the custom decimal separator functionality -- that was the original objective anyway.

**Comment by 3lvis** [comment]
Moved FORMTextField to [TextField](https://github.com/3lvis/TextField). This PR might need to be reopened when finished.

**Comment by jeffleeismyhero** [comment]
I was expecting that it would need to be rebuilt for that. I'll keep an eye on TextField and port the changes that are necessary to make it work.

**Pull request closed without merging**
