### PR TITLE
Improve: login demo

### PR DESCRIPTION
**Pull request by NSElvis**

### CODE REVIEW

**Comment by NSElvis** [comment]
@RamonGilabert should be ready now :)

**Comment by RamonGilabert** [comment]
Looks great for me! Great job @NSElvis! :)

**Comment by NSElvis** [comment]
@RamonGilabert feel free to merge it :)

**Comment by RamonGilabert** [comment]
@NSElvis I don't have access to it! :|

**Comment by NSElvis** [comment]
@RamonGilabert What about now?

screen shot 2015-03-01 at 2 56 59 pm

**Comment by RamonGilabert** [comment]
Done! Thank's @NSElvis! :)

**Pull request merged**
