### PR TITLE
Refactor FORMFieldValuesTableViewHeader

### PR DESCRIPTION
**Pull request by zenangst**
## Refactor initializer
FORMFieldValuesTableViewHeader is a UITableViewHeaderFooterView so
`initWithFrame` was never called.

The side effect of this was that the subview were never added to the
view.

## Use title instead of rawValue
This was causing issues when running it with a new version of Xcode.

```
[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance
0x7bb73b10
```

The initial value that was assigned to `.text` was a NSNumber and when
it tried to assign it to a string it couldn’t compare the two.

### CODE REVIEW

**Comment by richardoti** [comment]
I may guess, this is related to bridging with Swift, as `initWithReuseIdentifier` is a designated initializer.

**Comment by zenangst** [comment]
@richardoti well not really, in the case where I was using it, it doesn't use Swift.

**Comment by richardoti** [comment]
@zenangst I don't mean the issue is due to usage with Swift, but in general. I remember, Apple did some bridging with ObjC, so it may be related.

**Comment by 3lvis** [comment]
@zenangst Can we keep the old `initWithFrame` too for backwards compatibility?

**Comment by richardoti** [comment]
Is this issue relevant? #419

**Comment by zenangst** [comment]
@3lvis well, it was never called in the code so I felt that it was unnecessary to keep it around.

https://github.com/hyperoslo/Form/blob/master/Source/Cells/Popover/FORMFieldValuesTableViewController.m#L21

**Comment by richardoti** [comment]
Tested on Basic ObjC demo, works OK.

**Comment by 3lvis** [comment]
@zenangst makes sense :)

**Comment by 3lvis** [comment]
@richardoti It's great to get your feedback, you are super helpful, but could let merges to either @zenangst or me? :heart:  

https://github.com/hyperoslo/playbook/blob/master/GIT_AND_GITHUB.md#who-merges-the-pull-request

**Comment by richardoti** [comment]
@3lvis OK. @zenangst asked me to merge, so I think, this time it doesn't count. :sunglasses:

**Pull request merged**
