### PR TITLE
[WIP] Feature: multiselect

### PR DESCRIPTION
**Pull request by 3lvis**
Fixes => #242

### CODE REVIEW

**Comment by danr777** [comment]
Awesome, is it displaying back the selections though when the user selects it again

I just switched a "select" field to "multiselect"

 "id":"employment-1",
          "fields":[
            {
              "id":"base_salary",
              "title":"Base salary",
              "type":"multiselect",
              "size":{
                "width":25,
                "height":1
              },
              "values":[
                {
                  "title":"Salary 1",
                  "id":0,
                  "value":100.0,
                  "targets":[
                    {
                      "id":"total",
                      "type":"field",
                      "action":"update"
                    }
                  ]
                },
                {
                  "title":"Salary 2",
                  "id":1,
                  "value":200.0,
                  "targets":[
                    {
                      "id":"total",
                      "type":"field",
                      "action":"update"
                    }
                  ]
                },
                {
                  "title":"Salary 3",
                  "id":2,
                  "value":10.0,
                  "targets":[
                    {
                      "id":"total",
                      "type":"field",
                      "action":"update"
                    }
                  ]
                }
              ]
            }

**Comment by 3lvis** [comment]
@danr777 Not yet, is work in progress but that's the idea. 

I wonder what would be the best way to display the results though.

**Comment by danr777** [comment]
I think joining the stored value array with a ", " would look good inside of the field's textbox on a change or load.

Like per example previously: "Italian Food, Chinese Food"

What do you think?

**Comment by 3lvis** [comment]
@danr777 sounds like a good first iteration :)

**Comment by charbelhass** [comment]
hello,
can you work on this one so i can test it and finalise it.

**Comment by 3lvis** [comment]
Hey @charbelhass! This is going to take some work, my idea is making it like this:

multiselect

**Comment by charbelhass** [comment]
Yeah, this one is way better than a dropdown menu with multiple selection

**Comment by charbelhass** [comment]
:+1:

**Comment by charbelhass** [comment]
@3lvis man can you consider the implementation of 2 variables minimum selection and maximum selection, it would be a cool feature

**Comment by 3lvis** [comment]
@charbelhass would you mind making an issue explaining it? :)

**Comment by charbelhass** [comment]
@3lvis it is better after you finish the multiselection feature you talked about.
I meant that i a question is of type multi selection, the user can select answers as many as he wants like the image you posted before,
or
we can add minimum selection &/or maximum selection to the JSON so the user must select a number of answers between those to or greater than min or less than max
example of the image you posted, lets say we have maximum-selection = 3, the user can't select any more, he can select 1, 2 or 3 answers but not more.
same for min or both

**Comment by 3lvis** [comment]
Oh, I see. Of course :)

**Comment by charbelhass** [comment]
Hello, @3lvis any news on this one?

**Comment by 3lvis** [comment]
No progress coming soon; feel free to send a PR following the suggested design. :)

**Pull request closed without merging**
