### PR TITLE
 multiselect type storage/display & retrieval

### PR DESCRIPTION
**Pull request by danr777**
this is my first one for this, I hope I'm in spec with project style ( ? =-) )

Switching back to the answer has a slight problem I think (or the initial loading if a "selectedValues" was already defined? please help

### CODE REVIEW

**Comment by 3lvis** [comment]
@danr777 This looks very interesting. Thanks for your initiative :)

Travis is failing because a file is missing, it says

```
/Users/travis/build/hyperoslo/Form/Source/FORMDataSource.m:8:9: fatal error: 'FORMMultiselectFieldCell.h' file not found
#import "FORMMultiselectFieldCell.h"
```

Maybe you forgot to add it to git. Could you fix that?

**Comment by danr777** [comment]
I think that fixes it? not sure why that happened

**Comment by danr777** [comment]
I am not sure what is causing this? 

/Users/travis/build/hyperoslo/Form/Tests/Tests/FORMDataSourceTests.m:352:46: error: no visible @interface for 'NSDictionary' declares the selector 'hyp_dictionaryByRemovingNullItems'

**Comment by 3lvis** [comment]
@danr777 Your branch might be outdated.

That category of NSDictionary was renamed so the method is now called

`hyp_removingNulls`

https://github.com/hyperoslo/NSDictionary-HYPImmutable

**Comment by danr777** [comment]
sorry, I should not have pulled like that... I'm trying to revert, can't figure it out because it is a merge? Is it ok? :)

**Comment by danr777** [comment]
can someone cancel this pull request? :-1:

**Comment by 3lvis** [comment]
@danr777 Hey Dan, sorry for not giving the importance that it deserves to this issue, we are focusing on fixing some bugs when clearing fields, I'll make sure that we focus on multiselect once we are do with that.

Thanks!

**Comment by danr777** [comment]
thats fine with me! :)  this is coming out really nice  all of it

**Pull request closed without merging**
