### PR TITLE
Demo: modal storyboard

### PR DESCRIPTION
**Pull request by 3lvis**
For some reason the layout is not holding the dataSource, so it crashes. Everything else works just fine for https://github.com/hyperoslo/Form/issues/486

screen shot 2015-11-17 at 22 00 19

### CODE REVIEW

**Comment by 3lvis** [comment]
Any ideas on what's going on?

**Comment by 3lvis** [comment]
FORMViewController relays heavily on it's initializer. Using `initWithCoder` breaks the entire API. I suggest we just drop `initWithCoder` support and let people present their Forms programmatically.

**Comment by ehirebrandon** [comment]
please!

**Comment by richardoti** [comment]
@3lvis I remember having troubles with this part as well. In fact, there is little need to initialize Form completely in storyboard, at least from my point of view.

This framework is made to work in code, as the content is being generated using a JSON and can vary a lot. And setting `FORMLayout` in storyboard doesn't make it  easier to use. The level of the framework is not for beginners, so they should know how to initialize it proper way.

The only real need to use FORM Form with storyboards is to to be able to see general app flow and to configure navigation bar buttons with ease.

So I agree, it's totally fine to leave it as it is :smile:

**Comment by 3lvis** [comment]
Yeah, using Form without storyboards is simple enough.

**Pull request merged**
