### PR TITLE
Keep null values in the evaluator

### PR DESCRIPTION
**Pull request by zenangst**
I tried adding a rule to a dynamic field but those do not show up in
the dictionary because they are added without an initial value (NSNull).

### CODE REVIEW

**Comment by zenangst** [comment]
Also, you might want to add your own evaluator that something shouldn't be null and so on.

**Comment by 3lvis** [comment]
There was a reason why this was added. Can't remember at the moment. Have you tried this in your app without any issues? Do you prefer leaving adding tests for this to a new task, or you want to include some?

**Comment by zenangst** [comment]
So far I haven't seen any issue with it, might have been so that you could look for keys instead of values when doing `empty`. Gonna investigate it further tomorrow.

**Comment by zenangst** [comment]
@3lvis I think this is the reason why they were not included, fixed in https://github.com/hyperoslo/Form/commit/42a24bf980e3648b96d26447733d1d4f8e2d894a

**Pull request merged**
