### PR TITLE
Improve/decimal separator based on locale

### PR DESCRIPTION
**Pull request by aminiz**
Change to use NSLocaleDecimalSeparator instead of `,` in
FORMFloatInputValidator floatSet.

### CODE REVIEW

**Comment by 3lvis** [comment]
@zenangst would this cause any problems for you?

**Comment by 3lvis** [comment]
@aminiz could you please clean up this whitespaces?

screen shot 2016-05-03 at 23 13 54

**Comment by aminiz** [comment]
Sorry about that. Can you please take a look now.

**Comment by zenangst** [comment]
Might cause some issues, will have to investigate 🤔

**Comment by 3lvis** [comment]
@zenangst thanks!

**Comment by 3lvis** [comment]
@zenangst Any update on this? Should I just merge? Tests are passing.

**Comment by zenangst** [comment]
@3lvis haven't checked but I think you can merge, if there are any issues I'll look into them later and post a fix.

**Comment by 3lvis** [comment]
@zenangst 😗

**Comment by 3lvis** [comment]
Ships on https://github.com/hyperoslo/Form/releases/tag/3.10.1 

Thanks @aminiz 👏

**Pull request merged**
