### PR TITLE
multiselect field type demo data

### PR DESCRIPTION
**Pull request by danr777**
sample data for new field type multiselect

### CODE REVIEW

**Comment by jgorset** [comment]
Hey, thanks @danr777! Your indentation is sort of wacky, though, would you mind fixing?

**Comment by 3lvis** [comment]
This needs https://github.com/hyperoslo/Form/pull/302 to work

**Comment by danr777** [comment]
fixed indent, I will attempt this soon if you don't beat me to it.. i'm still trying to wrap my head around the project :)

**Comment by 3lvis** [comment]
Thanks @danr777 ! I'll try to work on this today, let's see where it takes us.

**Pull request merged**
