### PR TITLE
Add new logo

### PR DESCRIPTION
**Pull request by zenangst**

### CODE REVIEW

**Comment by NSElvis** [comment]
OMG, looks so pretty! What about adding the name of the thing next to the logo?

**Comment by NSElvis** [comment]
I've found that W: 2500px | H: 650px is the optimal dimension

**Comment by NSElvis** [comment]
@zenangst something like

dqwdqw

**Comment by zenangst** [comment]
I was going for something like this one - https://github.com/guard/guard

**Comment by NSElvis** [comment]
@zenangst I don't like that it breaks the readme and makes it harder to read, specially for us where we have bullet points.

**Comment by NSElvis** [comment]
@zenangst Overall it looks nicer in my opinion: https://github.com/Alamofire/Alamofire

**Comment by zenangst** [comment]
@NSElvis  Yah I agree that might be better for readability! You can go head and add your version to this commit and just merge if you like :)

**Comment by NSElvis** [comment]
@zenangst Should we have the sketch file in the repo?

**Comment by zenangst** [comment]
Why not, I just need to clean the Sketch file so that it's pretty before we do that :+1:

**Comment by NSElvis** [comment]
@zenangst hi!

**Comment by NSElvis** [comment]
@zenangst SOOOO GOOOOOD!

**Pull request merged**
