### PR TITLE
Improve form input validator

### PR DESCRIPTION
**Pull request by vadymmarkov**
Should fix "Range of index is out of bounds" exception.

### CODE REVIEW

**Comment by 3lvis** [comment]
Could you add a unit test for the failing case, please?

**Comment by zenangst** [comment]
TRAVIS! **waves fist**

**Comment by 3lvis** [comment]
Fucking Travis.

**Comment by vadymmarkov** [comment]
@3lvis @zenangst 
screen shot 2015-11-04 at 15 07 23

**Comment by 3lvis** [comment]
@vadymmarkov could you fix your 2 spaces instead of 4, plz?

**Comment by vadymmarkov** [comment]
@3lvis :scream: Yes, will do!

**Comment by 3lvis** [comment]
:tada:

**Pull request merged**
