### PR TITLE
func to invalidate fields

### PR DESCRIPTION
**Pull request by matteocrippa**
dunno if I missed something but I was interested in invalidating all the form resetting all the fields to empty status, so I managed to add this quick func

### CODE REVIEW

**Comment by NSElvis** [comment]
Hi @matteocrippa! 

By any chance have you tried `- (void)resetForms;`? 

https://github.com/matteocrippa/Form/blob/master/Source/FORMDataSource.h#L38

:smiley:

**Comment by matteocrippa** [comment]
@NSElvis yep, but it was totally removing the fields from the viewcontroller, my need was only eg to reset the UILabel to nil

**Comment by NSElvis** [comment]
Hi @matteocrippa, you're totally right, the `resetForms` is not acting as it should. I'll move your implementation to that method so you can use it.

Thanks!

**Comment by 3lvis** [comment]
Haha, wth.

**Comment by matteocrippa** [comment]
ops

**Pull request merged**
