### PR TITLE
Improve/structure

### PR DESCRIPTION
**Pull request by 3lvis**
- Change structure so demos point to `pod 'Form', path: "."`
- `xcproject` now lives in root folder (`wd form`, `xc`, works now)
- CocoaPods gives you better score for this structure

### CODE REVIEW

**Comment by 3lvis** [comment]
:tada:

**Comment by 3lvis** [comment]
:tada:

**Comment by 3lvis** [comment]
:tada:

**Comment by zenangst** [comment]
Could you add some tests for this?

giphy-60

**Comment by zenangst** [comment]
Wow, I just cloned the thing without thinking about what actually happened here. Such anarchy.

**Pull request merged**
