### PR TITLE
[WIP] Custom style

### PR DESCRIPTION
**Pull request by RamonGilabert**
Hey! :)

So which was your idea for the custom styling? I was thinking in the same way you set all the properties, lets say title, subtitle, etc. But for custom styles, backgroundColor, borderRadius, maybe shadow, etc. Right?

### CODE REVIEW

**Comment by NSElvis** [comment]
@RamonGilabert You can get more info here.

https://github.com/hyperoslo/Form/issues/198

The idea is to remove the hardcoded style and move to using `UIAppearance`, and for the layers do something like

```objc
- (void)setCornerRadius:(CGFloat)cornerRadius UI_APPEARANCE_SELECTOR;
```

http://timross.info/blog/2013/03/26/more-fun-with-uiappearance/

**Comment by RamonGilabert** [comment]
@NSElvis, yes, sorry about the `First Commit`, I did it to start the discussion.

Right, so instead of now having this:

```
self.layer.borderWidth = FORMFieldCellBorderWidth;
```

Have this:

```
[[FORMTextField appearance] setBorderWith: x];
```

And, the method to do that will be in the base class. But, for the user to be able to enter information, you want to enter it in the JSON file right? say:

```
"style": {
    "borderRadius": 30
}
```

**Comment by NSElvis** [comment]
@RamonGilabert You can skip the JSON part we don't need that, this can live in the app.

:tropical_drink: :palm_tree:

**Comment by RamonGilabert** [comment]
Ohhhhh! I see, so in the `FORMTextField` we're going to set the original value, then in the app, using one of the blogs we're going to be able to change that value, right? Then everything is the same, just adding those methods.

**Comment by NSElvis** [comment]
@RamonGilabert Do you mind cloning this project and making a PR on it? So I can make changes too? :dancers:

**Pull request closed without merging**
