### PR TITLE
Feature/add targets to dynamic fields

### PR DESCRIPTION
**Pull request by zenangst**

### CODE REVIEW

**Comment by zenangst** [comment]
@3lvis @vadymmarkov could you have a look?

**Comment by 3lvis** [comment]
@zenangst Would you mind adding a test for this?

**Comment by 3lvis** [comment]
Might suck if it gets rolled back

**Comment by zenangst** [comment]
@3lvis test added

**Comment by 3lvis** [comment]
@zenangst Awesome++

**Comment by zenangst** [comment]
@fespinoza, @JozoSalt might want to have a look at these changes

**Pull request merged**
