### PR TITLE
Add code coverage

### PR DESCRIPTION
**Pull request by 3lvis**
Still unsure if the Gemfile is needed but...   ¯\\_(ツ)_/¯

Followed this instructions => http://list.her.sh/ios-test-coverage-with-coveralls/

### CODE REVIEW

**Comment by 3lvis** [comment]
20673657_omg_reaction_gif

**Comment by orta** [comment]
You don't need a gemfile as you do `before_install: gem install cocoapods obcd slather -N` :+1:

**Comment by 3lvis** [comment]
@orta Thanks! This Test Jam is amazing.

**Comment by orta** [comment]
Make sure we have a note somehow so that it can be included in our writeup.

**Pull request merged**
