### PR TITLE
Collapsiblity boolean for group

### PR DESCRIPTION
**Pull request by jeffleeismyhero**
This feature adds support for defining whether or not a group is collapsible. By default, the behavior is the same, all groups are collapsible. By adding `"collapsible":false` to a group's JSON, you can prevent a group from being collapsed on click or through any of the other methods that would collapse groups.

**Sample JSON**

```JSON
[
  {
    "id":"personal-details",
    "title":"Personal Details",
    "collapsible":false,
    "sections":[
      {
        "id":"personal-details-0",
        "fields":[
          {
            "id":"first_name",
            "title":"First name",
            "info":"Fornavn",
            "type":"name",
            "size":{
              "width":30,
              "height":1
            },
            "validations":{
              "required":true,
              "min_length":2
            },
            "targets":[
              {
                "id":"display_name",
                "type":"field",
                "action":"update",
                "condition":"$username == 0"
              }
            ]
          },
          {
            "id":"last_name",
            "title":"Last name",
            "type":"name",
            "info":"Obs! Husk å kjøpe melk",
            "size":{
              "width":30,
              "height":1
            },
            "validations":{
              "required":true,
              "min_length":2
            },
            "targets":[
              {
                "id":"display_name",
                "type":"field",
                "action":"update",
                "condition":"$username == 0"
              }
            ]
          },
          {
            "id":"display_name",
            "title":"Display name",
            "info":"This is the name that is going to be used across the application.",
            "type":"text",
            "size":{
              "width":40,
              "height":1
            },
            "formula":"first_name last_name"
          }
        ]
      },
      {
        "id":"personal-details-1",
        "fields":[
          {
            "id":"address",
            "title":"Address",
            "type":"text",
            "size":{
              "width":50,
              "height":1
            }
          },
          {
            "id":"email",
            "title":"E-post",
            "info":"bork\nbork\nbork",
            "type":"email",
            "size":{
              "width":25,
              "height":1
            },
            "validations":{
              "format":"[\\w._%+-]+@[\\w.-]+\\.\\w{2,}",
              "required":true
            }
          },
          {
            "id":"username",
            "title":"Username",
            "type":"select",
            "size":{
              "width":25,
              "height":1
            },
            "values":[
              {
                "id":0,
                "title":"Generated",
                "info":"Generate using firstname & lastname",
                "default":true,
                "targets":[
                  {
                    "id":"first_name",
                    "type":"field",
                    "action":"enable"
                  },
                  {
                    "id":"last_name",
                    "type":"field",
                    "action":"enable"
                  },
                  {
                    "id":"display_name",
                    "type":"field",
                    "action":"disable"
                  }
                ]
              },
              {
                "id":1,
                "title":"Override",
                "info":"Enable manual editing for the display name",
                "targets":[
                  {
                    "id":"first_name",
                    "type":"field",
                    "action":"enable"
                  },
                  {
                    "id":"last_name",
                    "type":"field",
                    "action":"enable"
                  },
                  {
                    "id":"display_name",
                    "type":"field",
                    "action":"enable"
                  },
                  {
                    "id":"display_name",
                    "type":"field",
                    "action":"update"
                  }
                ]
              },
              {
                "id":2,
                "title":"Mr.Melk",
                "info":"Bork!",
                "targets":[
                  {
                    "id":"first_name",
                    "type":"field",
                    "action":"disable"
                  },
                  {
                    "id":"last_name",
                    "type":"field",
                    "action":"disable"
                  },
                  {
                    "id":"display_name",
                    "type":"field",
                    "action":"disable"
                  },
                  {
                    "id":"first_name",
                    "type":"field",
                    "action":"update",
                    "target_value":"Mr."
                  },
                  {
                    "id":"last_name",
                    "type":"field",
                    "action":"update",
                    "target_value":"Melk"
                  },
                  {
                    "id":"display_name",
                    "type":"field",
                    "action":"update"
                  },
                  {
                    "id":"contract_type",
                    "type":"field",
                    "action":"update",
                    "target_value":0
                  }
                ]
              },
              {
                "id":3,
                "title":"John Hyperseed",
                "info":"Other info",
                "targets":[
                  {
                    "id":"first_name",
                    "type":"field",
                    "action":"disable"
                  },
                  {
                    "id":"last_name",
                    "type":"field",
                    "action":"disable"
                  },
                  {
                    "id":"first_name",
                    "type":"field",
                    "action":"update",
                    "target_value":"John"
                  },
                  {
                    "id":"last_name",
                    "type":"field",
                    "action":"update",
                    "target_value":"Hyperseed"
                  },
                  {
                    "id":"display_name",
                    "type":"field",
                    "action":"update"
                  },
                  {
                    "id":"contract_type",
                    "type":"field",
                    "action":"update",
                    "target_value":1
                  }
                ]
              }
            ]
          },
          {
            "id":"image",
            "type":"image",
            "size":{
              "width":100,
              "height":1.7
            }
          }
        ]
      }
    ]
  },
  {
    "id":"employment",
    "title":"Employment",
    "collapsed":true,
    "sections":[
      {
        "id":"employment-0",
        "fields":[
          {
            "id":"start_date",
            "title":"Start date",
            "info":"The day of employment",
            "type":"date",
            "size":{
              "width":25,
              "height":1
            }
          },
          {
            "id":"start_time",
            "title":"Start time",
            "type":"time",
            "size":{
              "width":25,
              "height":1
            }
          },
          {
            "id":"end_date",
            "title":"End date",
            "type":"date",
            "validations":{
              "compare_to":"start_date",
              "compare_rule":">"
            },
            "size":{
              "width":25,
              "height":1
            }
          },
          {
            "id":"end_time",
            "title":"End time",
            "type":"time",
            "size":{
              "width":25,
              "height":1
            },
            "validations":{
              "required":true,
              "min_length":2
            }
          },
          {
            "id":"contract_type",
            "title":"Contract type",
            "info":"Type of contract\n Permanent or temporary",
            "type":"select",
            "size":{
              "width":50,
              "height":1
            },
            "values":[
              {
                "id":0,
                "title":"Permanent",
                "info":"Regular employee",
                "default":true,
                "targets":[
                  {
                    "id":"end_date",
                    "type":"field",
                    "action":"show"
                  },
                  {
                    "id":"end_time",
                    "type":"field",
                    "action":"show"
                  },
                  {
                    "id":"employment-1",
                    "type":"section",
                    "action":"show"
                  }
                ]
              },
              {
                "id":1,
                "title":"Temporary",
                "targets":[
                  {
                    "id":"end_date",
                    "type":"field",
                    "action":"hide"
                  },
                  {
                    "id":"end_time",
                    "type":"field",
                    "action":"hide"
                  },
                  {
                    "id":"employment-1",
                    "type":"section",
                    "action":"hide"
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        "id":"employment-1",
        "fields":[
          {
            "id":"base_salary",
            "title":"Base salary",
            "type":"select",
            "size":{
              "width":25,
              "height":1
            },
            "values":[
              {
                "title":"Salary 1",
                "id":0,
                "value":100,
                "targets":[
                  {
                    "id":"total",
                    "type":"field",
                    "action":"update"
                  }
                ]
              },
              {
                "title":"Salary 2",
                "id":1,
                "value":200,
                "targets":[
                  {
                    "id":"total",
                    "type":"field",
                    "action":"update"
                  }
                ]
              },
              {
                "title":"Salary 3",
                "id":2,
                "value":10,
                "targets":[
                  {
                    "id":"total",
                    "type":"field",
                    "action":"update"
                  }
                ]
              }
            ]
          },
          {
            "id":"bonus_enabled",
            "title":"Bonus enabled",
            "type":"select",
            "size":{
              "width":25,
              "height":1
            },
            "values":[
              {
                "id":true,
                "title":"Ja"
              },
              {
                "id":false,
                "title":"Nei"
              }
            ]
          },
          {
            "id":"bonus",
            "title":"Bonus",
            "type":"float",
            "size":{
              "width":25,
              "height":1
            },
            "targets":[
              {
                "id":"total",
                "type":"field",
                "action":"update"
              }
            ]
          },
          {
            "id":"total",
            "title":"Total",
            "type":"float",
            "size":{
              "width":25,
              "height":1
            },
            "disabled":true,
            "formula":"$base_salary + $bonus"
          }
        ]
      }
    ]
  }
]
```

### CODE REVIEW

**Comment by 3lvis** [comment]
@jeffleeismyhero For some reason Travis was disabled, could you make sure that all the unit tests are running?

**Comment by jeffleeismyhero** [comment]
All of the tests pass. If I'm not mistake, Travis was replaced with CircleCI and it was disabled after failing to run entirely: https://circleci.com/gh/hyperoslo/Form/15

See PR #441

**Comment by 3lvis** [comment]
I've enabled Travis for this repo again :)

**Comment by 3lvis** [comment]
Looks good to me!

**Comment by 3lvis** [comment]
@jeffleeismyhero please update the README to show this feature if you have some time :kissing_heart:

**Comment by jeffleeismyhero** [comment]
Sure will! Thanks!

**Comment by 3lvis** [comment]
Thanks to you!

**Pull request merged**
